# Site settings
title: 迷茫的年轻人
SEOTitle: Heiyogl 的博客 测试 | BY Blog
header-img: img/post-bg-desk.jpg
email: heiyogl@163.com
description: "Heiyogl.个人分享博客  config description"
keyword: "Java, MySQL, Spring, Redis, Hbase, Heiyogl 的博客 测试, Heiyogl, Emperor, BY Blog"
url: "http://heiyogl.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/heiyogl/heiyogl.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "右侧介绍"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     heiyogl.test
zhihu_username:     heiyogl.test
github_username:    heiyogl.test
facebook_username:  heiyogl.test
jianshu_username:   heiyogl.test
#twitter_username:   heiyogl.test




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: heiyogl.test

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 3660b4b40df6c88aa587   #生成的clientID
  clientSecret: b44d1817548e8eede929d5efc176fc93e45bd7db  #同上
  repo: heiyogl.github.io    #仓库名称
  owner: heiyogl    #github用户名
  admin: heiyogl
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
@ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
@ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://heiyogl.test.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/heiyogl.test"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
